-- ========================================
-- VERTRAVELS DATABASE SCHEMA
-- Migration 0018: Disable RLS on admin tables
-- PostgreSQL (Supabase)
-- ========================================

ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotations DISABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE partners DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE modules DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_gateways DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_role_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE agencies DISABLE ROW LEVEL SECURITY;
ALTER TABLE bsp_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE bsp_line_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE bsp_reconciliation DISABLE ROW LEVEL SECURITY;
ALTER TABLE manual_postings DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_statements DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_receipts DISABLE ROW LEVEL SECURITY;
ALTER TABLE auto_ticketing_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE automation_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE tickets DISABLE ROW LEVEL SECURITY;
ALTER TABLE booking_workflow DISABLE ROW LEVEL SECURITY;
ALTER TABLE iata_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE iata_tracking DISABLE ROW LEVEL SECURITY;
ALTER TABLE partner_payouts DISABLE ROW LEVEL SECURITY;
ALTER TABLE commission_tracking DISABLE ROW LEVEL SECURITY;
